"""Initial commit

Revision ID: b9c83e1e8509
Revises: 
Create Date: 2024-07-05 19:26:05.472799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9c83e1e8509"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "state",
            sa.Enum("work", "down", "unstable", name="statechoice"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "servicestatehistory",
        sa.Column(
            "time_in",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("time_out", sa.DateTime(timezone=True), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("work", "down", "unstable", name="statechoice"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("servicestatehistory")
    op.drop_table("service")
    # ### end Alembic commands ###
